# Generated by Django 5.2.13 on 2026-05-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedata',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='encrypted_files/'),
        ),
    ]
