# Generated by Django 5.2.13 on 2026-05-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption_app', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
