# Generated by Django 5.2.13 on 2026-05-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('encryption_app', '0004_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(  # Adhula AlterField nu irukkum, Adhai AddField nu maathidunga
            model_name='securedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
